[package]
name = "ture"
version = "0.1.0"
authors = ["Isac Fadoni <@o_inodaf>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]